Repository nextmcloud/nmctheme, pull requests merged in 2023-10, with the labels that each got.

#111 Viewer design - minor fixes
  css/apps/viewer.scss
Labels: bug, custom

#113 Sharing style update
  css/apps/sharing.scss
  css/components/ncactions.scss
  dist/icons.css
  img/actions/attachment.svg
  package.json
  src/icons.mjs
Labels: custom

#114 Upload progress bar
  css/components/upload.scss
  css/nmcstyle.scss
  src/icons.mjs
Labels: custom

#116 styling for custom settings components
  css/apps/settings.scss
Labels: custom

#118 added icons for email settings
  css/apps/settings.scss
  img/actions/auto-login.svg
  img/email/opened.svg
  src/icons.mjs
Labels: custom

#119 Nmc/2554 header user menu customization
  css/apps/settings.scss
  lib/AppInfo/Application.php
  lib/L10N/FactoryDecorator.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/NavigationManagerDecorator.php
  src/components/UserMenu.vue
  src/index.d.ts
  src/nmcheader.ts
  src/vue.d.ts
  webpack.config.cjs
Labels: custom

#115 Add line breaks for smartphone
  css/layouts/footer.scss
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#124 added modifications to files app navigation menu
  css/v25/ncappnavigation.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/AppInfo/Application.php
  lib/NavigationManagerDecorator.php
  lib/Service/NMCFilesService.php
Labels: custom

#126 'My shares' and 'Shared with me' views - icons
  .eslintrc.cjs
  css/apps/files.scss
  css/components/tooltip.scss
  css/nmcstyle.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/Listener/BeforeTemplateRenderedListener.php
  package-lock.json
  package.json
  src/js/shareicons.js
  src/js/tooltip.js
  webpack.config.cjs
Labels: custom

#125 revert footer column layout changes
  css/layouts/footer.scss
  l10n/de.json
  l10n/de_DE.json
Labels: custom

#127 final touches to settings page
  css/apps/settings.scss
  img/settings/warning.svg
  src/icons.mjs
  webpack.config.cjs
Labels: custom

#128 My shares - Fix incorrect icon display
  src/js/shareicons.js
Labels: bug, custom

#130 file list 100%
  css/apps/files.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/Service/NMCFilesService.php
  src/components/StorageQuota.vue
Labels: custom

#131 Viewer app - fix icon colors for dark and light modes
  css/apps/viewer.scss
Labels: custom

#132 File grid view
  css/apps/files_grid.scss
  css/nmcstyle.scss
Labels: custom

#135 final changes
  css/apps/files.scss
  img/actions/toggle-filelist.svg
  img/actions/toggle-pictures.svg
  src/icons.mjs
Labels: custom

#136 Nmc/2551 file list 100
  css/components/ncbreadcrumb.scss
  src/icons.mjs
Labels: custom

#137 corrected icon color
  css/apps/files.scss
Labels: custom

#138 Upload bar - Set inner label color to white
  css/components/upload.scss
Labels: custom

#143 Restyle guest view for shared folders and files
  css/apps/apps.scss
  css/layouts/guestview.scss
  css/nmcstyle.scss
Labels: custom

#140 fixed colors
  css/_mixins.scss
  css/apps/files.scss
  css/apps/settings.scss
  css/components/ncactions.scss
  css/components/ncbuttons.scss
  css/layouts/modal.scss
  css/nmcstyle.scss
  css/v25/ncappnavigation.scss
Labels: custom

#145 applied scale style to dialog boxes
  css/layouts/modal.scss
Labels: custom

#146 replaced restore icon in trashbin view
  css/apps/files.scss
  img/actions/restore.svg
  src/icons.mjs
Labels: custom

#144 Restyle header spacings and font styles
  css/components/ncappmenu.scss
  css/layouts/header.scss
Labels: custom

#147 Media/Photos app - general styling
  css/apps/media.scss
  css/components/ncactions.scss
  css/components/ncappnavigation.scss
  css/nmcstyle.scss
  img/icons/play-video.svg
  src/icons.mjs
Labels: custom

#148 final touches to filelist and dialog boxes
  css/apps/files.scss
  css/apps/settings.scss
  css/components/ncappnavigation.scss
  css/components/ncusermenu.scss
  css/layouts/modal.scss
  css/v25/ncappnavigation.scss
Labels: custom

#151 Applied telekom design in text tool
  css/apps/files.scss
  css/apps/rich-workspace.scss
  css/nmcstyle.scss
  img/rich-workspace/alert.svg
  img/rich-workspace/bold.svg
  img/rich-workspace/callout.svg
  img/rich-workspace/checklist.svg
  img/rich-workspace/code.svg
  img/rich-workspace/emoji.svg
  img/rich-workspace/h1.svg
  img/rich-workspace/h2.svg
  img/rich-workspace/h3.svg
  img/rich-workspace/h4.svg
  img/rich-workspace/h5.svg
  img/rich-workspace/h6.svg
  img/rich-workspace/help.svg
  img/rich-workspace/image.svg
  img/rich-workspace/italic.svg
  img/rich-workspace/ol.svg
  img/rich-workspace/quote.svg
  img/rich-workspace/redo.svg
  img/rich-workspace/strikethrough.svg
  img/rich-workspace/success.svg
  img/rich-workspace/table-settings.svg
  img/rich-workspace/table.svg
  img/rich-workspace/ul.svg
  img/rich-workspace/underline.svg
  img/rich-workspace/undo.svg
  img/rich-workspace/warning.svg
  src/icons.mjs
Labels: custom

#156 Sidebar navigation - styling fixes
  css/_mixins.scss
  css/components/ncappnavigation.scss
  css/components/ncbuttons.scss
  css/nmcdefault.scss
  css/v25/ncappnavigation.scss
  src/components/StorageQuota.vue
Labels: custom

#157 My shares - fix icons not rendering if only one share exists
  src/js/shareicons.js
Labels: bug

#159 applied folder creation behavior to files
  css/apps/files.scss
  src/js/newfilemenuplugin.js
Labels: custom

#158 Restyle password entry page for guest view only
  css/layouts/guestview.scss
Labels: custom

#161 added translation of email label with dash
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#162 Remove all transition animations for header menu
  css/components/ncappmenu.scss
  css/components/ncheadermenu.scss
Labels: custom

#163 Change background image for error page view
  css/layouts/status.scss
Labels: custom

#164 adjusted grid menu multiselect functions
  css/apps/files.scss
  css/apps/files_grid.scss
Labels: custom

#166 added missing icons
  img/filetypes/file.svg
  img/filetypes/x-office-document.svg
  img/filetypes/x-office-drawing.svg
Labels: custom

#165 fixed delete file bug
  src/js/filelistplugin.js
  src/js/newfilemenuplugin.js
Labels: bug, custom

#167 corrected color of icons
  css/apps/rich-workspace.scss
  img/rich-workspace/bold.svg
  img/rich-workspace/code.svg
  img/rich-workspace/h1.svg
  img/rich-workspace/h2.svg
  img/rich-workspace/h3.svg
  img/rich-workspace/h4.svg
  img/rich-workspace/h5.svg
  img/rich-workspace/h6.svg
  img/rich-workspace/italic.svg
  img/rich-workspace/ol.svg
  img/rich-workspace/quote.svg
  img/rich-workspace/strikethrough.svg
  img/rich-workspace/table-settings.svg
  img/rich-workspace/table.svg
  img/rich-workspace/ul.svg
  img/rich-workspace/underline.svg
Labels: bug, custom

#171 Storage quota - show two digits after comma
  src/components/StorageQuota.vue
Labels: bug, custom

#172 Viewer - icon and label updates
  css/apps/viewer.scss
  css/components/ncactions.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#177 Correct mimetype icon mapping for pdf
  img/filetypes/pdf.svg
  resources/config/mimetypealiases.json
Labels: bug, custom

#178 Files right click menu
  css/apps/files-right-click.scss
  css/layouts/guestview.scss
  css/nmcstyle.scss
  img/actions/cut-paste.svg
  src/icons.mjs
Labels: custom

#180 Right click menu
  css/apps/apps.scss
  css/apps/files-right-click.scss
  img/actions/compress-zip.svg
  img/actions/richdocuments.svg
  src/icons.mjs
Labels: custom

#181 Media and albums
  css/apps/media.scss
  css/components/ncappnavigation.scss
  css/components/ncheadermenu.scss
Labels: custom

#176 No search providers shown on UI
  lib/AppInfo/Application.php
  lib/Search/SearchComposerDecorator.php
Labels: bug, custom
