Repository nextmcloud/nmctheme, pull requests merged in 2023-09, with the labels that each got.

#47 Add custom conflict dialog
  css/layouts/conflictdialog.scss
  css/nmcstyle.scss
  js/icons.mjs
  lib/Listener/BeforeTemplateRenderedListener.php
  src/js/conflictdialog.js
  src/js/filessettings.js
  src/js/nmcfooter.js
  webpack.config.cjs
Labels: custom

#52 Brand logo with title and multiFont-Logo support
  README.adoc
  lib/Listener/BeforeTemplateRenderedListener.php
  src/l10nappender.ts
  src/nmclogo.ts
  src/tests/l10nappender.test.ts
  tsconfig.json
  webpack.config.cjs
Labels: custom

#50 E2e encryption translations
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#55 Icon update, various style fixes
  css/_mixins.scss
  css/apps/files.scss
  css/components/ncappnavigation.scss
  css/components/ncbreadcrumb.scss
  css/components/nccheckbox.scss
  css/layouts/conflictdialog.scss
  css/layouts/header.scss
  css/layouts/login.scss
  css/nmcstyle.scss
  css/v25/header.scss
  css/v25/ncappnavigation.scss
  img/actions/home.svg
  img/actions/upload.svg
  img/breadcrumb-arrow.svg
  img/filetypes/folder-regular.svg
  js/filelist_icons.js
  js/icons.mjs
  lib/Listener/BeforeTemplateRenderedListener.php
  src/components/FilesSettings.vue
  src/components/StorageQuota.vue
  webpack.config.cjs
Labels: custom

#56 Translations: Add alternate constructors for V25, V26 for AppendService injection
  lib/L10N/L10NResourceLocatorExtension.php
Labels: custom

#61 (nmc 2480 v25stable) fix logo position and footer width
  css/layouts/footer.scss
  css/layouts/header.scss
  css/layouts/user.scss
Labels: custom

#60 Fix login style for consent layer behavior
  css/layouts/footer.scss
  css/layouts/login.scss
Labels: custom

#62 general settings app styling and user menu fix
  css/apps/apps.scss
  css/components/ncappmenu.scss
  css/components/ncheadermenu.scss
  css/layouts/conflictdialog.scss
  css/layouts/footer.scss
  css/layouts/header.scss
  css/layouts/login.scss
  css/layouts/user.scss
  css/v25/header.scss
  css/v25/ncappnavigation.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  src/components/UserMenu.vue
  src/components/UserMenuItem.vue
  src/js/nmcsettings.js
Labels: custom

#65 move background image into correct folder
  css/apps/apps.scss
  img/telekom/mcfluffy.jpg
Labels: custom

#66 add alignment for arrow button, chkboxes and chkbox text
  css/components/ncappnavigation.scss
  css/components/nccheckbox.scss
Labels: custom

#63 Theme standard Nextcloud mime type mapping mechanism
  appinfo/routes.php
  img/filetypes/3 unknown file.svg
  img/filetypes/folder-share-old.svg
  img/filetypes/folder.svg
  img/filetypes/font.svg
  img/filetypes/voice-recordings.svg
  js/filelist_icons.js
  lib/AppInfo/Application.php
  lib/Controller/MimeIconController.php
  lib/JSResourceLocatorExtension.php
  lib/Listener/BeforeTemplateRenderedListener.php
  resources/config/mimetypealiases.json
  resources/config/mimetypemapping.json
  src/js/mimetypes.js
  webpack.config.cjs
Labels: custom

#64 Change photos app navigation entry to Medien/Media
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/L10N/FactoryDecorator.php
  lib/Listener/BeforeTemplateRenderedListener.php
Labels: custom

#67 Customize file selection
  css/apps/files.scss
  css/components/ncheadermenu.scss
  css/v25/header.scss
  css/v25/ncappnavigation.scss
  lib/Listener/BeforeTemplateRenderedListener.php
  src/components/UserMenu.vue
  src/js/filelistplugin.js
  webpack.config.cjs
Labels: custom

#74 Move translation from settings to theme
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#78 Fix filesize computations, use binary metrics
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  src/components/StorageQuota.vue
Labels: custom

#76 Use displayname and translations in settings menu context
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  src/js/nmcsettings.js
Labels: custom

#75 created newfilemenu plugin
  lib/Listener/BeforeTemplateRenderedListener.php
  src/js/filelistplugin.js
  src/js/newfilemenuplugin.js
  webpack.config.cjs
Labels: custom

#80 Acquire Nextcloud standard web packing and settings
  .gitignore
  composer.json
  css/apps/viewer.scss
  dist/icons.css
  img/actions/folder.svg
  img/actions/play-next.svg
  img/actions/play-previous.svg
  img/actions/play.svg
  lib/Listener/BeforeTemplateRenderedListener.php
  package.json
  src/icons.mjs
  src/index.d.ts
  src/main.js
  src/tests/tsconfig.json
  webpack.config.cjs
Labels: custom, dependencies

#83 Restrict supported languages in theme
  README.adoc
  lib/L10N/FactoryDecorator.php
  tests/unit/L10N/DecoratorTest.php
  tests/unit/L10N/FactorySupportedLangTest.php
  tests/unit/L10N/FactoryTest.php
  tests/unit/L10N/FactoryTestCase.php
  tests/unit/L10N/L10nTest.php
  tests/unit/UrlGeneratorDecoratorTest.php
Labels: custom

#86 Remove functional Parts of nmcsettings from nmcthemes
  css/apps/settings.scss
  css/v25/ncappnavigation.scss
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/Listener/BeforeTemplateRenderedListener.php
  src/components/UserMenu.vue
  src/js/nmcsettings.js
Labels: custom

#87 removed nmcsettings from webpack config
  webpack.config.cjs
Labels: custom

#92 modified layout of filelist multiselection
  css/apps/apps.scss
  css/apps/files.scss
  css/apps/settings.scss
  css/layouts/footer.scss
  css/layouts/header.scss
  img/actions/copy-paste.svg
  src/icons.mjs
  src/js/filelistplugin.js
Labels: custom

#95 fixed filtering of available languages
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/L10N/FactoryDecorator.php
  tests/unit/L10N/FactorySupportedLangTest.php
  tests/unit/L10N/FactoryTestCase.php
Labels: bug, custom

#98 Display settings -> 'Show folder info text' option
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  src/components/DisplaySettings.vue
  src/components/filesSettings.utils.ts
  src/store/userconfig.ts
Labels: custom

#100 added adaptations for filelist
  css/apps/files.scss
  src/js/filelistplugin.js
Labels: custom

#102 style update for nmcsettings
  css/apps/settings.scss
Labels: custom

#103 Previewer design
  css/apps/viewer.scss
  css/nmcstyle.scss
Labels: custom

#105 style update for nmcsettings
  css/apps/settings.scss
Labels: custom

#107 Revert @nextcloud/vue version
  package-lock.json
  package.json
Labels: bug, custom

#109 added nmc wide selection rule
  css/apps/files.scss
  css/apps/server.scss
  css/nmcstyle.scss
Labels: custom
