Repository nextmcloud/nmctheme, pull requests merged in 2023-11, with the labels that each got.

#187 Header - change font weight of labels
  css/layouts/header.scss
  css/v25/header.scss
Labels: custom

#186 Media and albums - icons and layout
  css/apps/media.scss
  img/device/camera.svg
  img/device/photo-camera.svg
  img/media/albums.svg
  img/media/all-media.svg
  src/icons.mjs
Labels: custom

#185 Right click menu
  css/apps/files-right-click.scss
Labels: custom

#184 Guest view - update layout
  css/_mixins.scss
  css/layouts/guestview.scss
Labels: custom

#183 File conflict dialog
  css/_variables.scss
  css/apps/apps.scss
  css/apps/files.scss
  css/apps/settings.scss
  css/components/ncappnavigation.scss
  css/components/ncheadermenu.scss
  css/layouts/conflictdialog.scss
  css/layouts/footer.scss
  css/layouts/guestview.scss
  css/layouts/header.scss
  css/v25/ncappnavigation.scss
  src/js/conflictdialog.js
Labels: custom

#189 Hide 'Shared' label in mobile view
  css/apps/files.scss
Labels: custom

#188 Sidebar navigation of Media app - Change hide menu icon
  css/apps/media.scss
  img/actions/hide-menu.svg
  src/icons.mjs
Labels: custom

#190 Fix grid view layout
  css/apps/files.scss
Labels: bug

#193 Replace icon for text file
  img/filetypes/text.svg
Labels: custom

#191 Disarranged checkbox fix
  css/apps/media.scss
  css/components/nccheckbox.scss
  src/components/DisplaySettings.vue
Labels: bug, custom

#192 Restyle Unified Search & Results Popover
  css/components/ncheadermenu.scss
  css/components/search.scss
  css/nmcstyle.scss
Labels: custom

#196 Media - remove share button for Albums
  css/apps/media.scss
Labels: custom

#197 Media - rename "Edit Album details"
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#198 Media -> Remove menu entry "Shared with you"
  css/apps/media.scss
Labels: custom

#199 modified media menu entry and all media icon
  css/apps/media.scss
  img/media/photos-videos.svg
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  lib/L10N/FactoryDecorator.php
  src/icons.mjs
Labels: custom

#202 fix for sidebar menu on ipad/iphone
  css/v25/ncappnavigation.scss
  src/icons.mjs
Labels: custom

#203 hide colum on file update
  l10n/de.json
  l10n/de_DE.json
  src/js/filelistplugin.js
Labels: custom

#205 FIX Windows - Email validation - Info text above the "Confirm" button is hard to read
  css/layouts/login.scss
Labels: custom

#206 Media - Remove upload functionality from Add photos function
  css/apps/media.scss
Labels: custom

#208 Header - minor layout updates
  css/components/ncappmenu.scss
  css/nmcdefault.scss
Labels: custom

#207 fixed file creation
  package-lock.json
  src/js/filelistplugin.js
  src/js/newfilemenuplugin.js
Labels: custom

#211 Restyle Media-> Album -> Add photos modal
  css/apps/media.scss
Labels: custom

#213 Empty album view
  css/apps/media.scss
Labels: custom

#214 Media -> Remove Title from Add Photos Modal
  css/apps/media.scss
Labels: custom

#215 fixed sidebar behavior
  src/js/filelistplugin.js
  src/js/newfilemenuplugin.js
Labels: custom

#216 Media and albums - hide links in sidebar navigation
  css/apps/media.scss
Labels: custom

#218 Media Restyle Folder section
  css/apps/photos.scss
  css/nmcstyle.scss
Labels: custom

#219 modified login header bubble
  css/layouts/login.scss
  img/telekom/mcbubble-text.svg
Labels: custom

#220 Photos - No albums view
  css/apps/photos.scss
Labels: custom

#223 Fix Files Impossible to download a video image on PRE1
  lib/AppInfo/Application.php
  lib/Listener/CSPListener.php
Labels: custom

#224 fixed bubble size and icons
  css/apps/rich-workspace.scss
  img/rich-workspace/file.svg
  img/rich-workspace/link.svg
  src/icons.mjs
Labels: custom

#225 fixed csp listener
  lib/Listener/CSPListener.php
Labels: custom

#226 Hide 'Edit locally' on right click
  css/apps/files-right-click.scss
Labels: custom

#227 Replace icon for Albums page
  img/media/albums.svg
Labels: custom

#229 Revert Nmc/2675 configure csp for public pages
  lib/AppInfo/Application.php
  lib/Listener/CSPListener.php
Labels: custom

#231 Increase min-height of text app editor
  css/apps/rich-workspace.scss
Labels: custom

#230 Restyle Login Grant Window and small changes in Media Add Photo Modal and 3-Dot-Menu
  css/apps/photos.scss
  css/components/ncactions.scss
  css/login/grant.scss
  css/nmcstyle.scss
Labels: custom

#234 restored autoshow fuctionality
  css/apps/rich-workspace.scss
Labels: custom

#235 replaced delete icon in link bubble
  css/apps/rich-workspace.scss
  img/actions/light-dark.svg
  img/rich-workspace/alert.svg
  img/rich-workspace/danger.svg
  img/rich-workspace/warning.svg
  src/icons.mjs
Labels: custom

#236 made edit button visible again
  css/apps/viewer.scss
  css/components/ncbuttons.scss
Labels: custom

#237 Photos app changes
  css/apps/photos.scss
  css/apps/sharing.scss
Labels: custom

#239 fixed button padding
  css/apps/viewer.scss
  css/components/ncbuttons.scss
Labels: custom

#240 Fix grant login window paragraph and button issue
  css/login/grant.scss
Labels: custom

#241 Media (Photos App) Album 3-dot-menu Restyle
  css/apps/photos.scss
  css/components/ncactions.scss
  img/actions/arrow-left.svg
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
  src/icons.mjs
Labels: custom

#242 added uppercase translation variant
  l10n/de.json
  l10n/de_DE.json
  l10n/en.json
  l10n/en_GB.json
Labels: custom

#243 removed color overrides
  css/apps/rich-workspace.scss
Labels: custom

#245 hide reset password link
  css/layouts/guestview.scss
Labels: custom

#244 added create file functionality for public pages
  src/js/newfilemenuplugin.js
Labels: custom

#246 added office filetype determination
  src/js/newfilemenuplugin.js
  src/utils/types.js
Labels: custom
